### obtener todos los datos
GET http://localhost:3000/user?limit=10&page=8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDUxMzA1NCwiZXhwIjoxNzQ0NTE2NjU0fQ.pfximNQB7-E1i6nlTrTGhyOv-mdNNJsYGTFw1IDmAOo
###
GET http://localhost:3000/user/20833991-5


#### filtro
http://localhost:3000/user/filtro?limit=10&page=2&carrera=Ingeniería%20en%20Control%20de%20Gestión
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDUxMzA1NCwiZXhwIjoxNzQ0NTE2NjU0fQ.pfximNQB7-E1i6nlTrTGhyOv-mdNNJsYGTFw1IDmAOo


###

### Crear usuario 
POST http://localhost:3000/user/crear
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDI1MDgxOCwiZXhwIjoxNzQ0MjU0NDE4fQ.4KDUjm7hKSKoElmDYonAlq_uHxJzaZg98L0xbDFoPjo
Content-Type: application/json

{
  "rut": "4578840-7",
  "nombre": "Austin Beier",
  "carrera": "Contador auditor"
}
### Actualizar usuario
PUT http://localhost:3000/user/actualizar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDI1MTU3NywiZXhwIjoxNzQ0MjU1MTc3fQ.uVsehYILygmNJUqCPj3mwrtVzj1SBKURbsymop-ubq4

{
  "rut": "4578840-7"
}
### acutalizar usuario
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "usuario": "admin1",
  "contrasenia":"admin123"
}
###
PUT http://localhost:3000/user/actualizarUsuario/20833991-5
Content-Type: application/json

{
  "nombre": "Francisco Concha ",
  "carrera": "Ingeniería en Control de Gestión",
  "rutB": "20833982-6 "
}


