### obtener todos los datos
GET http://localhost:3000/user?limit=10&page=8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDUxMzA1NCwiZXhwIjoxNzQ0NTE2NjU0fQ.pfximNQB7-E1i6nlTrTGhyOv-mdNNJsYGTFw1IDmAOo
###
GET http://localhost:3000/user/20833991-5


#### filtro
http://localhost:3000/user/filtro?limit=10&page=2&carrera=Ingeniería%20en%20Control%20de%20Gestión
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDUxMzA1NCwiZXhwIjoxNzQ0NTE2NjU0fQ.pfximNQB7-E1i6nlTrTGhyOv-mdNNJsYGTFw1IDmAOo


###

### Crear usuario 
POST http://localhost:3000/user/crear
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NTAzMDE1OSwiZXhwIjoxNzQ1MDMzNzU5fQ.KhUxaCuDvfToLbduzDOVKnDchIp11E-a7QUqGeQWJhY
Content-Type: application/json

{
  "rut": "19444496-6",
  "nombre": "Carlos Concha",
  "carrera": "Contador auditor"
}
### Actualizar usuario
PUT http://localhost:3000/user/actualizar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NTAzMTQzNiwiZXhwIjoxNzQ1MDM1MDM2fQ.vJ0o3NoIqK1r3gj5DYV21ytptDujaa5qPeGkmSmptqs

{
  "rut": "4578840-7"
}
### acutalizar usuario
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "usuario": "admin1",
  "contrasenia":"admin123"
}
###
PUT http://localhost:3000/user/actualizarUsuario/20833991-5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NTAyNjQ5NywiZXhwIjoxNzQ1MDMwMDk3fQ.NI9UgtY6BN91VLngaODtoOYzJncUnJWqLyDFqjTKS14
Content-Type: application/json

{
  "nombre": "Francisco Concha ",
  "carrera": "Ingeniería en Control de Gestión",
  "rutB": "20833982-6"
}


