### obtener todos los datos
GET http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDMwNTcxNCwiZXhwIjoxNzQ0MzA5MzE0fQ.7l6EMnDk4QnSA1fcJn6DDi_RItO2v6u6m93mZvI0mlY

### obtener un dato
GET http://localhost:3000/user/20833982-6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDMwMzc0NCwiZXhwIjoxNzQ0MzA3MzQ0fQ.U4Rj0Vj5HMQMo4kgQyrr2vIw10RB7J6GJ6DglSRGvcQ


#### filtro
http://localhost:3000/user/filtro?isActive=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDMwNTcxNCwiZXhwIjoxNzQ0MzA5MzE0fQ.7l6EMnDk4QnSA1fcJn6DDi_RItO2v6u6m93mZvI0mlY


###

### Crear usuario 
POST http://localhost:3000/user/crear
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDMwNTcxNCwiZXhwIjoxNzQ0MzA5MzE0fQ.7l6EMnDk4QnSA1fcJn6DDi_RItO2v6u6m93mZvI0mlY
Content-Type: application/json

{
  "rut": "21713690-3",
  "nombre": "javier aaguirre",
  "carrera": "Contador auditor"
}
### Actualizar usuario
PUT http://localhost:3000/user/actualizar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc0NDMwOTM0OSwiZXhwIjoxNzQ0MzEyOTQ5fQ.55uJi4AV7f8sQPX4dKmv3ZCNbGdCQENjPtrlk64FzgA

{
  "rut": "12345678-9"
}
### acutalizar usuario
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "usuario": "admin1",
  "contrasenia":"admin123"
}


